// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvtpwflhburnlkwbvnsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2dHB3ZmxoYnVybmxrd2J2bnN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5MjU1MDgsImV4cCI6MjA3NzUwMTUwOH0.g-kEUiyR6KmTnOZ63-dpijrqduIXJ57AX69sfn5zRbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});